### ISSUE TITLE
Black Map

### ISSUE THREAD

**Issue by Ploximity** [SleepKiller/swbfii-shaderpatch#1]
Whenever I load in a map, everything is black.

**Comment by RepComm** [comment]
Sounds like the same affect as when using a map without texture files. If you stick a server version of the map's lvls in with the client, you can see this affect.

**Comment by SleepKiller** [comment]
I think I may know what is causing this. I've started up a wiki page for keeping track of common problems people have and solutions to them. Check it out [here](https://github.com/SleepKiller/swbfii-shaderpatch/wiki/Common-Problems-&-Solutions#when-i-load-a-map-everything-in-the-world-is-black).

(By common problems I mean things that aren't directly bugs in Shader Patch and are more likely configuration problems with the end user.)
