### ISSUE TITLE
Sun flares are Messed up in v0.6.0

### ISSUE THREAD

**Issue by SleepKiller** [SleepKiller/swbfii-shaderpatch#16]
I haven't exhaustively looked into it yet, but seems to be something to do with the "hooking" points used for the alternate Blur effects. 

![star wars battlefront ii 11_07_2018 12_19_58 am](https://user-images.githubusercontent.com/5582558/42509526-54793cc8-84a0-11e8-93a0-61a81f0c60a4.png)

**Comment by MartinBFFan** [comment]
I can also confirm they are visible through all objects and map geometry.
![20180710081139_1](https://user-images.githubusercontent.com/34067979/42515884-184c16fa-845d-11e8-82c9-0a70249a96a6.jpg)

**Comment by SleepKiller** [comment]
Fixed by aa262dbed5ead025171adc7727e94a1727ef1f87 and e4c8bb9450501dfd35ec3429405a87e79fbf1c58.
