### ISSUE TITLE
Envmapping Bugs 

### ISSUE THREAD

**Issue by Calrissian97** [SleepKiller/swbfii-shaderpatch#19]
### Envmapping results in duller models in some cases
![envmapbug2](https://user-images.githubusercontent.com/37759131/43012096-6d062984-8c13-11e8-9b3d-5553cba59f3e.png)
Left Stock, Right Shaderpatch

### There are sometimes bugs with large objects with cubemaps, often resulting in them looking stretched at certain angles
![envmapbug](https://user-images.githubusercontent.com/37759131/43012424-305c2794-8c14-11e8-898c-3f61b0d30933.png)
Left Stock, Right Shaderpatch 

*This **might** be an intel-bug!*

**Comment by SleepKiller** [comment]
I believe I have fixed these in e05f010. Obviously just let me know if that doesn't seem to have been the case. Here's is a build you test out if you like with that commit in it [shaderpatch-e05f010.zip](https://github.com/SleepKiller/swbfii-shaderpatch/files/2222095/shaderpatch-e05f010.zip).
